In [1]:
import importlib
import sys
import os

sys.path.append(
    os.path.abspath("../data_prepration")
)
import load_data
importlib.reload(load_data)

### **products table duplicates check**

In [ ]:
products = load_data.load_products()
dups_count = products.duplicated().sum()
dups_count

np.int64(0)

### **products table missing value check**

In [3]:
missing_values_count = products.isna().sum()
missing_values_count

product_id     0
category       0
subcategory    0
price          0
launch_date    0
is_active      0
dtype: int64

### **products table primary uniqueness check**

In [4]:
products["product_id"].is_unique

True

### **category distribution**

In [9]:
products_by_category = (
    products
        .groupby("category")
        .agg(
            products_count = ("product_id", "count")
        )
        .sort_values("products_count", ascending = False)
)
products_by_category["perccentage"] = (products_by_category["products_count"] / products_by_category["products_count"].sum()).round(4)
products_by_category.to_csv("../../output/products_by_category.csv")
products_by_category

             products_count  perccentage
category
Electronics            4293       0.2862
Fashion                3540       0.2360
Home                   2647       0.1765
Beauty                 1810       0.1207
Sports                 1483       0.0989
Books                  1227       0.0818

### **subcategory distribution**

In [11]:
products_by_subcategory = (
    products
        .groupby(["category", "subcategory"])
        .agg(
            products_count = ("product_id", "count")
        )
        .sort_values("products_count", ascending = False)
)
products_by_subcategory["percentage"] = (products_by_subcategory["products_count"] / products_by_subcategory["products_count"].sum()).round(4)
products_by_subcategory.to_csv("../../output/products_by_subcategory.csv")
products_by_subcategory

                         products_count  percentage
category    subcategory
Electronics Accessories            1112      0.0741
            Laptops                1080      0.0720
            Phones                 1073      0.0715
            Gaming                 1028      0.0685
Fashion     Women                   895      0.0597
            Watches                 890      0.0593
            Men                     886      0.0591
            Shoes                   869      0.0579
Home        Decor                   707      0.0471
            Furniture               661      0.0441
            Kitchen                 652      0.0435
            Lighting                627      0.0418
Beauty      Makeup                  626      0.0417
            Perfumes                596      0.0397
            Skincare                588      0.0392
Sports      Outdoor                 503      0.0335
            Cycling                 491      0.0327
            Fitness                 489      0.0326
Books       Fiction                 420      0.0280
            Business                409      0.0273
            Technology              398      0.0265

### **Products Distribution by Active Status**

In [14]:
products_by_active_status = (
    products
        .groupby("is_active")
        .agg(
            products_count = ("product_id", "count")
        )
)
products_by_active_status["percentage"] = (products_by_active_status["products_count"] / products_by_active_status["products_count"].sum()).round(4)
products_by_active_status.to_csv("../../output/products_by_active_status.csv")
products_by_active_status

           products_count  percentage
is_active
False                 737      0.0491
True                14263      0.9509